services:
  app:
    image: bloglist-frontend-dev
    build:
      context: ./bloglist-frontend/ # The context will pick this directory as the "build context"
      dockerfile: ./dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./bloglist-frontend/:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    container_name: bloglist-frontend-dev # This will name the container hello-front-dev
    depends_on:
      - server


  server:
    image: bloglist-backend-dev
    build:
      context: ./bloglist-backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./bloglist-backend/:/usr/src/app
    environment: 
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: bloglist-backend-dev
  mongo:
    image: mongo
    restart: always
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./bloglist-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./bloglist-backend/mongo_data:/data/db


  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server

  debug-helper:
    image: busybox